project:
  type: website
  output-dir: docs

website:
  title: "REBECCA JENNIFER"
  navbar:
    right:
      - text: "Education"
        menu:
          - text: "Computer Systems and Assembly Course"
            href: education/comp-org.qmd
          - text: "How to Learn"
            href: education/how-to-learn.qmd
      - text: "ColorClock"
        href: color-clock.qmd
      - text: "Contact"
        href: index.qmd

format:
  html:
    theme: default
    css: flux-bunny.css
    code-fold: true