project:
  type        : website
  output-dir  : docs
  resources   :
    - assets/ui-elements/**

website:
  title: "Rebecca Jennifer Rashkin"
  navbar:
    right:
      - text: "Education"
        menu:
          - text: "How to Learn"
            href: education/how-to-learn.qmd
          - text: "Computer Systems and Assembly Course"
            href: education/comp-org/comp-org.qmd
          - text: How to View Worksheet Answers
            href: education/comp-org/worksheet-answers.qmd

      - text: "ColorClock"
        href: color-clock.qmd
      - text: "Contact"
        href: index.qmd

format:
  html:
    theme: default
    css: flux-bunny.css
    code-fold: true